//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.11 at 11:47:10 AM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.oclc.org/dsdl/schematron", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.oclc.purl.dsdl.schematron;
