//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.11 at 11:47:10 AM BRST 
//


package org.oclc.purl.dsdl.schematron;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://purl.oclc.org/dsdl/schematron}foreign"/>
 *         &lt;element ref="{http://purl.oclc.org/dsdl/schematron}include"/>
 *         &lt;choice>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}title"/>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}ns"/>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}p"/>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}let"/>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}phase"/>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}pattern"/>
 *           &lt;element ref="{http://purl.oclc.org/dsdl/schematron}diagnostics"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://purl.oclc.org/dsdl/schematron}rich"/>
 *       &lt;attGroup ref="{http://purl.oclc.org/dsdl/schematron}foreign"/>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="schemaVersion" type="{http://purl.oclc.org/dsdl/schematron}non-empty-string" />
 *       &lt;attribute name="defaultPhase" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="queryBinding" type="{http://purl.oclc.org/dsdl/schematron}non-empty-string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anyOrAnyOrInclude"
})
@XmlRootElement(name = "schema")
public class Schema {

    @XmlElementRefs({
        @XmlElementRef(name = "let", namespace = "http://purl.oclc.org/dsdl/schematron", type = Let.class),
        @XmlElementRef(name = "pattern", namespace = "http://purl.oclc.org/dsdl/schematron", type = Pattern.class),
        @XmlElementRef(name = "ns", namespace = "http://purl.oclc.org/dsdl/schematron", type = Ns.class),
        @XmlElementRef(name = "diagnostics", namespace = "http://purl.oclc.org/dsdl/schematron", type = Diagnostics.class),
        @XmlElementRef(name = "title", namespace = "http://purl.oclc.org/dsdl/schematron", type = Title.class),
        @XmlElementRef(name = "p", namespace = "http://purl.oclc.org/dsdl/schematron", type = P.class),
        @XmlElementRef(name = "phase", namespace = "http://purl.oclc.org/dsdl/schematron", type = Phase.class),
        @XmlElementRef(name = "include", namespace = "http://purl.oclc.org/dsdl/schematron", type = Include.class)
    })
    @XmlAnyElement
    protected List<Object> anyOrAnyOrInclude;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "schemaVersion")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String schemaVersion;
    @XmlAttribute(name = "defaultPhase")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object defaultPhase;
    @XmlAttribute(name = "queryBinding")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String queryBinding;
    @XmlAttribute(name = "icon")
    protected String icon;
    @XmlAttribute(name = "see")
    protected String see;
    @XmlAttribute(name = "fpi")
    protected String fpi;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the anyOrAnyOrInclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyOrAnyOrInclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyOrAnyOrInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Let }
     * {@link Pattern }
     * {@link Ns }
     * {@link Diagnostics }
     * {@link Title }
     * {@link P }
     * {@link Element }
     * {@link Phase }
     * {@link Include }
     * 
     * 
     */
    public List<Object> getAnyOrAnyOrInclude() {
        if (anyOrAnyOrInclude == null) {
            anyOrAnyOrInclude = new ArrayList<Object>();
        }
        return this.anyOrAnyOrInclude;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the defaultPhase property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDefaultPhase() {
        return defaultPhase;
    }

    /**
     * Sets the value of the defaultPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefaultPhase(Object value) {
        this.defaultPhase = value;
    }

    /**
     * Gets the value of the queryBinding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryBinding() {
        return queryBinding;
    }

    /**
     * Sets the value of the queryBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryBinding(String value) {
        this.queryBinding = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the see property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSee() {
        return see;
    }

    /**
     * Sets the value of the see property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSee(String value) {
        this.see = value;
    }

    /**
     * Gets the value of the fpi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpi() {
        return fpi;
    }

    /**
     * Sets the value of the fpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpi(String value) {
        this.fpi = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
